export type { Theme, Difficulty, GameMode } from './types.js'

const ACCENT_AGG = /^[A-Z]+$/

export function normalize(word: string): string {
  return word
    .toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/Œ/g, 'OE')
    .replace(/Æ/g, 'AE')
    .replace(/[^A-Z]/g, '')
}

const STOP_WORDS = new Set<string>([
  'LE','LA','LES','UN','UNE','DES','DE','DU','ET','OU','EN','DANS','SUR','POUR','AVEC',
])

export type WordsModule = {
  all: string[]
  byTheme: Record<string, string[]>
  themeList: string[]
}

let wordsModule: WordsModule | null = null

const THEME_FILTERS: Record<string, (w: string) => boolean> = {
  animaux: (w) =>
    /(CHAT|CHIEN|VACHE|CHEVAL|MOUTON|COCHON|POULE|LION|TIGRE|ELEPHANT|SINGE|OURS|RENNARD|RENARD|LAPIN|SOURIS|RAT|OISEAU|AIGLE|PIGEON|MOINEAU|SERPENT|TORTUE|POISSON|REQUIN|BALEINE|DAUPHIN|CRABE|CREVETTE|CIGALE|FOURMI|ABEILLE|MOUTON|CHEVRE|ANE|VACHE|TAUREAU|GENISSE|BISON|CERF|BICH|RATON|MARMOTTE|ECUREUIL|LIEVRE|FAISAN|PERDRIX|CANARD|OIE|CYGNE|PAON|TOUCAN|PERROQUET|KOALA|PANDA|GIRAFE|ZEBRE|HIPPOPOTAME|RHINOCEROS|CROCODILE|IGUANE|LEZARD|GRENOUILLE|CRAPAUD|ESCARGOT|LIMACE|ARAIGNEE|MOUSTIQUE|MOUCHE|GUEPE|FRELON|CIGALE|SAUTERELLE|GRILLON|COCCINELLE|PAPILLON|CHENILLE|VER|MILLEPATTE|SCORPION|CRABE|HOMARD|LANGOUSTE|PIEUVRE|CALMAR|SEICHE|MEDUSE|ETOILEMER|HUITRE|MOULE|PALOURDE|COQUILLAGE|CORAIL|ESCADARGOT|TATOU|PARESSEUX|OTARIE|PHOQUE|MORSE|MANCHOT|PINGOUIN|AUTRUCHE|FLAMANT|PELICAN|CIGOGNE|HERON|CIGOGNE|MOUETTE|GOELAND|ALBATROS|PINGOUIN|FOQUE)$/.test(w)
    || /(CHAT|CHIEN|LION|TIGRE|OURS|ANE|CHEVAL|VACHE|MOUTON|COCHON|POULE|LAPIN|SOURIS|RAT|SINGE|GIRAFE|ZEBRE|PANDA|KOALA|AIGLE|PIGEON|MOINEAU|SERPENT|TORTUE|REQUIN|BALEINE|DAUPHIN|ESCARGOT|GRENOUILLE|ARAIGNEE|MOUSTIQUE|MOUCHE|ABEILLE|PAPILLON|CIGALE|CANARD|OIE|CYGNE|FAISAN|LIEVRE|ECUREUIL|CERF|CHEVRE|MARMOTTE|OTARIE|PHOQUE|MANCHOT|FLAMANT|AUTRUCHE|HOMARD|CALMAR|PIEUVRE|MEDUSE|LIMACE|CRAPAUD|LIZARD|LEZARD|IGUANE|CROCODILE|GRENOUILLE|GUEPE|FOURMI|SAUTERELLE|GRILLON|COCCINELLE|CHENILLE)/.test(w),
  nourriture: (w) =>
    /(PAIN|FROMAGE|BEURRE|LAIT|YAOURT|CREME|OEUFS|OMELETTE|JAMBON|SAUCISS|PATES|RIZ|PATATE|POMMEDETERRE|TOMATE|SALADE|CAROTTE|OIGNON|AIL|COURGETTE|AUBERGINE|POIVRON|CHAMPIGNON|FRAMBOISE|FRAISE|CERISE|RAISIN|BANANE|ORANGE|CITRON|POMME|POIRE|PECHE|ABRICOT|MELON|PASTEQUE|KIWI|ANANAS|MANGUE|AVOCAT|BANANE|CHOCOLAT|BONBON|CAKE|GATEAU|TARTE|CROISSANT|BAGUETTE|PIZZA|BURGER|FRITES|SANDWICH|CREPE|GAUFRE|SOUFFLE|PUREE|MOUTARDE|MAYONNAISE|KETCHUP|SEL|POIVRE|SUCRE|FARINE|LEVURE|HUILE|VINAIGRE|CONFITURE|MIEL|CAFÉ|CAFE|THE|JUS|EAU|VIN|BIERE|CHAMPAGNE|SAUCISSON|SALAMI|TERRINE|PATE|BISCUIT|COOKIE|GLACE|SORBET|SUSHI|NOUILLES|CASSOULET|POTEE|RACLETTE|FONDUE|TARTIFLETTE|GASpACHO|RATATOUILLE|BOEUF|VEAU|PORC|POULET|DINDE|CANARD|PIGEON|SAUMON|THON|TRUITE|CABILLAUD|MORUE|MORUE|SOLE|CABILLAUD|STPIERRE|COLIN|ANCHOIS|SARDINE|HARENG|ESPADON|CARPE|BROCHET|SILURE|MORUE|CREVETTE|HOMARD|LANGOUSTE|CRABE|MOULE|HUITRE|PALOURDE|COQUILLE|BULOT|ENCORNET|SEICHE)/.test(w),
  cinema: (w) =>
    /(FILM|CINEMA|ACTEUR|ACTRICE|REALISATEUR|SCENARISTE|MONTAGE|BANDE|ANNONCE|BANDEANNONCE|TRAILER|TEASER|DOUBLAGE|SOUSTITRE|OSCARS|CESAR|CANNES|FESTIVAL|AVANTPREMIERE|PROJECTION|SALLE|CINEMA|DRIVE|SCENARIO|SCRIPT|STORYBOARD|CLAP|PERCHE|DECORDAGE|TOURNAGE|DOUBLURE|CASC|STUNTMAN|EFFETSSPECIAUX|3D|IMAX|POP|CORN|CINEMA|FILM|HOLLYWOOD|BOLLYWOOD|STAR|CELEBRITE|REMAKE|ADAPTATION|SEQUELLE|PREQUEL|SPIN|FRANCHISE|EPISODE|SAGA|TRILOGIE|TETRALOGIE|GENRE|COMEDIE|TRAGEDIE|DRAME|THRILLER|HORREUR|EPouvante|FANTASTIQUE|SF|SCIENCE|FICTION|AVENTURE|ACTION|ROMANCE|ANIMATION|MANGA|ANIME|DOCUMENTAIRE|BIO|BIOGRAPHIE|WESTERN|POLAR|GUERRE|MUSICAL|COMEDIE|MUSICALE)/.test(w),
  sport: (w) =>
    /(FOOT|FOOTBALL|RUGBY|TENNIS|BASKET|BASKETBALL|VOL|VOLLEY|VOLLEYBALL|HANDBALL|HOCKEY|BASEBALL|CRICKET|GOLF|BADMINTON|SQUASH|PADEL|NATATION|PLONGEON|CRAWL|BRASSE|PAPILLON|DOS|NAGE|WATER|POLO|VOILE|AVIRON|canoE|KAYAK|RAFTING|ESCALADE|ALPINISME|SKI|SNOWBOARD|SURF|BODY|KITE|WIND|PLANCHE|ROUL|CYCLISME|VELO|BMX|VTT|COURSE|MARATHON|SPRINT|DECATHLON|HEPTATHLON|TRIATHLON|LANCER|SAUT|PERCHE|HAUTEUR|LONGUEUR|TRIPLE|JAVELOT|MART|DISQUE|POIDS|MART|MARCHE|RANDONNEE|TREKKING|COURSE|ORIENTATION|BOXE|JUDO|KARATE|TAEKWONDO|AIKIDO|LUTTE|ESCRIME|TIR|TIRARC|ARC|COURSE|REL|HALTER|PHIL|GYMNASTIQUE|ACROBATIE|TRAMPOLINE|DANSE|PATIN|PATINAGE|BOBSLEIGH|LUGE|SKELETON|CURLING|BIATHLON|COMBINE|FOND|SAUTASKI|FREESTYLE|SNOW|BOARD|FREE|RIDE|HALF|PIPE|BIG|AIR|SLOPE|STYLE|CROSS|MOTOCROSS|ENDURO|TRIAL|CIRCUIT|RALLYE|FORMULE|F1|NASCAR|INDY|MOTOGP|SUPER|BIKE|SUPER|MOTO|ENDURANCE|VTT|DESCENTE|DRAPEAU|BUT|ESSAI|PENALTY|COUP|FRANC|TOUCHE|CORNER|HORS|JEU|MONTANT|PERDU|GAGNE|CHAMPION|COUPE|MEDAILLE|TROPHEE|JO|OLYMPIQUE|JO)/.test(w),
  geographie: (w) =>
    /(FRANCE|ALLEMAGNE|ANGLETERRE|ESPAGNE|PORTUGAL|ITALIE|BELGIQUE|PAYS|BAS|SUISSE|AUTRICHE|POLOGNE|RUSSE|UKRAINE|GRECE|TURQUIE|MEXIQUE|BRESIL|ARGENTINE|CHILI|PEROU|COLOMBIE|CANADA|ETATS|UNIS|USA|JAPON|CHINE|COREE|INDE|VIETNAM|THAILANDE|MAROC|ALGERIE|TUNISIE|EGYPTE|SENEGAL|MALI|NIGER|TCHAD|SOUDAN|ETHIOPIE|KENYA|TANZANIE|AFRIQUE|SUD|MADAGASCAR|CAP|VERDE|AUSTRALIE|NOUVELLE|ZELANDE|PAPOUASIE|INDONESIE|PHILIPPINES|VIETNAM|COREE|NORD|SUD|MONGOLIE|KAZAKHSTAN|IRAN|IRAK|ARABIE|SAOUDITE|EMIRATS|QATAR|KOWEIT|LIBAN|SYRIE|JORDANIE|ISRAEL|PALESTINE|CHYPRE|MALTE|CROATIE|SERBIE|BOSNIE|SLOVENIE|MONTENEGRO|MACEDOINE|ALBANIE|BULGARIE|ROUMANIE|MOLDAVIE|BIELORUSSIE|LITUANIE|LATVIE|ESTONIE|FINLANDE|SUEDE|NORVEGE|DANEMARK|ISLANDE|IRLANDE|ECOSSE|PAYS|GALLES|LUXEMBOURG|LIECHTENSTEIN|ANDORRE|MONACO|VATIC|SAN|MARINO|MONT|BLANC|ALPES|PYRENEES|HIMALAYA|ANDES|ROCHEUSES|AMAZONE|NIL|GANGE|DANUBE|RHIN|LOIRE|SEINE|VOLGA|MEKONG|THAMES|SAHARA|GOBI|KALAHARI|NAMIB|ATACAMA|PACIFIQUE|ATLANTIQUE|INDIEN|ARCTIQUE|ANTARCTIQUE|MEDITERRANEE|NOIRE|ROUGE|JAUNE|BALTIQUE|NORD|MANCHE|ADRIATIQUE|EGEE|IONIENNE|TYRRHENIENNE|CASPIENNE|ARAL|MORT|MEDITERRANEE|BAIKAL|TITICACA|VICTORIA|TANGANYIKA|NASSER|PARIS|LYON|MARSEILLE|BORDEAUX|LILLE|TOULOUSE|NICE|NANTES|STRASBOURG|RENNES|MONTPELLIER|BORDEAUX|GRENOBLE|LONDRES|BERLIN|MADRID|ROME|LISBONNE|BRUXELLES|AMSTERDAM|VIENNE|VARSOVIE|MOSCOU|KIEV|ATHENES|ANKARA|LE|CAIRE|TOKYO|PEKIN|SEOUL|NEWDELHI|BANGKOK|RIO|BUENOS|AIRES|LIMA|BOGOTA|CARACAS|HAVANE|KINGSTON|OTTAWA|WASHINGTON|NEWYORK|LOSANGELES|CHICAGO|HOUSTON|PHOENIX|MONTREAL|TORONTO|VANCOUVER|SYDNEY|MELBOURNE|PERTH|AUCKLAND|WELLINGTON|HANOI|SAIGON|SINGAPOUR|JAKARTA|MANILLE|KUALA|LUMPUR|TEHERAN|BAGHDAD|RIYADH|DUBAI|DOHA|KOWEIT|BEYROUTH|DAMAS|AMMAN|TEL|AVIV|JERUSALEM|NICOSIE|LA|VALLETTE|ZAGREB|BELGRADE|SARAJEVO|LJUBLJANA|PODGORICA|SKOPJE|TIRANA|SOFIA|BUCHAREST|CHISINAU|MINSK|VILNIUS|RIGA|TALLINN|HELSINKI|STOCKHOLM|OSLO|COPENHAGUE|REYKJAVIK|DUBLIN|EDIMBOURG|CARDIFF|LUXEMBOURG|VADUZ|ANDORRE|MONACO)/.test(w),
  objets: (w) =>
    /(CHAISE|TABLE|BUREAU|COMMODE|ARMOIRE|LIT|CANAPE|FAUTEUIL|TABOURET|BANC|ETAGERE|BIBLIOTHEQUE|LAMPE|ABAT|JOUR|PLAFONNIER|LUSTRE|LAMPE|TORCHE|BOUGIE|BOUGEOIR|VEILLEUSE|RADIO|TELE|TELEVISEUR|ORDINATEUR|PORTABLE|TABLETTE|SMARTPHONE|TELEPHONE|CLAVIER|SOURIS|ECRAN|MONITEUR|IMPRIMANTE|SCANNEUR|ENCEINTE|CASQUE|MICRO|MICROPHONE|WEBCAM|ROUTEUR|MODEM|PRISE|RALLONGE|MULTIPRISE|INTERRUPTEUR|PRISE|AMP|POUBELLE|BALAI|SERPILLIERE|ASPIRATEUR|SEP|EASY|MOP|SPON|PANOS|ESSUIE|TORCHON|CHIFFON|SERVIETTE|NAPPERON|TAPIS|MOQUETTE|PARQUET|CARRELAGE|LINOLEUM|RIDEAU|VOILAGE|STORE|BAGUETTE|TABLEAU|MIROIR|CADRE|PORTE|MANTEAU|PANIER|PORTEMANTEAU|POTE|POTT|POT|BOUGIE|PARFUM|SAVON|BROSSE|PEIGNE|BROSSEDENTS|RASOIR|SERVIETTE|BROSSE|TIRE|BOUCHE|EAU|TOILETTE|TAPIS|BAIN|DOUCHE|POMMEAU|ROBINET|LAVABO|BIDE|TOILETTES|CHASSE|MIROIR|MEDICAMENT|ARMOIRE|PHARMACIE|THERMOMETRE|TENS|STETO|SERINGUE|PANSEMENT|COMPRESSE|BANDAGE|ATTELLE|BEQUILLE|FAUTEUIL|ROULANT|LUNETTES|JUMELLES|LOUPE|MICROSCOPE|TELESCOPE|JUMELLES|BOUSSOLE|BARIOMETRE|THERMOMETRE|HORLOGE|MONTRE|REVEIL|SABLIER|CHRONOMETRE|COMPTEUR|BOITE|COFFRE|MALLE|VALISE|SAC|CABAS|PORTEFEUILLE|PORTEMONNAIE|TROUSSE|SERVIETTE|PORTE|DOCUMENT|CLASSEUR|CHEMISE|POCHE|RUBAN|ADHESIF|CISEAUX|CUTTER|RÈGLE|EQUERRE|COMPAS|STYLO|BIC|CRAYON|FEUTRE|MARQUEUR|SURLIGNEUR|GOMME|TAILLECRAYON|CORRECTEUR|ENCRE|CARTOUCHE|CLAI|REPROGRAPHIE|COPIE|CALQUE|PAPIER|FEUILLE|CAHIER|CARNET|BLOC|BLOC|NOTES|POST|IT|AGENDA|CALENDRIER|PLANNING|EPONGE|ESSUIE|PLAT|BOL|ASSIETTE|COUTEAU|FOURCHETTE|CUILLERE|CUILLERE|SALADIER|LOUCHE|CUILLERE|BATTEUR|FILTR|PASSOIRE|CHAUFFE|PLAT|PLATEAU|PLAQUE|GRILLE|FOUR|MICRO|ONDES|FRIGO|REFRIGERATEUR|CONGELATEUR|LAVE|VAISSELLE|LAVE|LINGE|SECHE|LINGE|CUISINIERE|PLAQUE|GAZ|ELECTRIQUE|INDUCTION|FOURNEAU|ROBOT|BLENDER|MIXEUR|PERCOLATEUR|CAFETIERE|THEIERE|BOUILLOIRE|GRILLE|PAIN|TOAST|PRESSOIR|CITRON|RAPER|EPLUCHE|LEGUME|CONSERVE|OUVRE|BOITE|TIRE|BOUCHON|BOUCHON|LIMONADE|BOUTEILLE|CRUCHE|CARAFE|GOBELET|VERRE|FLUTE|COUPE|GOBELET|MUG|TASSE|SOUCOUPE|POT|JARDINIERE|POT|FLEUR|VASE|CACHE|POT|ARROSOIR|BINETTE|RATEAU|Pelle|Pelle|BECHE|PIOCHE|SCIE|MARTEAU|TOURNEVIS|CLE|PINCE|TENAILLE|SECEAU|Echelle|ESCARPOT|TAPE|MESURE|RUBAN|METRE|NIVEAU|FIL|PLOMB|LASER|EQUERRE|CRAYON|MAITRE)/.test(w),
}

function classifyWord(word: string): string[] {
  const themes: string[] = []
  for (const [theme, fn] of Object.entries(THEME_FILTERS)) {
    if (fn(word)) themes.push(theme)
  }
  return themes
}

export function buildWords(allWords: string[]): WordsModule {
  const byTheme: Record<string, string[]> = {}
  const themeList = ['quotidien', 'animaux', 'nourriture', 'cinema', 'sport', 'geographie', 'objets', 'absurde', 'mix']
  for (const t of themeList) byTheme[t] = []
  for (const w of allWords) {
    if (!ACCENT_AGG.test(w)) continue
    if (w.length < 4 || w.length > 12) continue
    if (STOP_WORDS.has(w)) continue
    const themes = classifyWord(w)
    if (themes.length === 0) {
      byTheme['quotidien'].push(w)
    } else {
      for (const t of themes) byTheme[t].push(w)
    }
  }
  byTheme['mix'] = allWords.filter((w) => ACCENT_AGG.test(w) && w.length >= 4 && w.length <= 12)
  for (const t of themeList) {
    byTheme[t] = [...new Set(byTheme[t])]
  }
  return { all: allWords, byTheme, themeList }
}

export function loadWords(words: string[]): WordsModule {
  if (!wordsModule) wordsModule = buildWords(words)
  return wordsModule
}

export function getWords(): WordsModule {
  if (!wordsModule) throw new Error('Words module not loaded')
  return wordsModule
}

const DIFFICULTY_LEN: Record<string, [number, number]> = {
  facile: [4, 6],
  normal: [5, 9],
  expert: [7, 12],
}

function shuffle<T>(arr: T[]): T[] {
  const out = [...arr]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

export function pickWords(
  theme: string,
  difficulty: string,
  count: number,
  exclude: Set<string> = new Set(),
  seedWords?: string[],
  mod?: WordsModule
): string[] {
  const m = mod ?? getWords()
  const list = theme === 'mix' || !m.byTheme[theme]
    ? (seedWords ?? m.all)
    : m.byTheme[theme]
  const [min, max] = DIFFICULTY_LEN[difficulty] ?? DIFFICULTY_LEN.normal
  const filtered = list.filter((w) => w.length >= min && w.length <= max && !exclude.has(w))
  if (filtered.length === 0) {
    const fallback = m.all.filter((w) => w.length >= min && w.length <= max && !exclude.has(w))
    return shuffle(fallback).slice(0, count)
  }
  return shuffle(filtered).slice(0, count)
}

export function pickOne(
  theme: string,
  difficulty: string,
  exclude: Set<string> = new Set(),
  seedWords?: string[],
  mod?: WordsModule
): string {
  const arr = pickWords(theme, difficulty, 1, exclude, seedWords, mod)
  return arr[0]
}

export function isForbiddenClue(clue: string, secret: string): { forbidden: boolean; reason?: string } {
  const c = normalize(clue)
  const s = normalize(secret)
  if (!c) return { forbidden: false }
  if (c === s) return { forbidden: true, reason: 'identique' }
  if (c.length >= 3 && s.includes(c)) return { forbidden: true, reason: 'contenu_dans_secret' }
  if (c.length >= 3 && c.includes(s)) return { forbidden: true, reason: 'contient_secret' }
  const prefix = commonPrefix(c, s)
  if (prefix.length >= 4 && Math.min(c.length, s.length) - prefix.length <= 2) {
    return { forbidden: true, reason: 'racine_commune' }
  }
  const lev = levenshtein(c, s)
  if (c.length >= 4 && s.length >= 4 && lev <= 1) {
    return { forbidden: true, reason: 'trop_proche' }
  }
  return { forbidden: false }
}

function commonPrefix(a: string, b: string): string {
  let i = 0
  while (i < a.length && i < b.length && a[i] === b[i]) i++
  return a.slice(0, i)
}

function levenshtein(a: string, b: string): number {
  const m = a.length
  const n = b.length
  if (m === 0) return n
  if (n === 0) return m
  const dp: number[][] = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0))
  for (let i = 0; i <= m; i++) dp[i][0] = i
  for (let j = 0; j <= n; j++) dp[0][j] = j
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
        dp[i - 1][j - 1] + cost,
      )
    }
  }
  return dp[m][n]
}
